// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "github.com/lenon/portfolios/internal/models"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// CorporateActionRepository is an autogenerated mock type for the CorporateActionRepository type
type CorporateActionRepository struct {
	mock.Mock
}

type CorporateActionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CorporateActionRepository) EXPECT() *CorporateActionRepository_Expecter {
	return &CorporateActionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: action
func (_m *CorporateActionRepository) Create(action *models.CorporateAction) error {
	ret := _m.Called(action)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.CorporateAction) error); ok {
		r0 = rf(action)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CorporateActionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CorporateActionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - action *models.CorporateAction
func (_e *CorporateActionRepository_Expecter) Create(action interface{}) *CorporateActionRepository_Create_Call {
	return &CorporateActionRepository_Create_Call{Call: _e.mock.On("Create", action)}
}

func (_c *CorporateActionRepository_Create_Call) Run(run func(action *models.CorporateAction)) *CorporateActionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.CorporateAction))
	})
	return _c
}

func (_c *CorporateActionRepository_Create_Call) Return(_a0 error) *CorporateActionRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CorporateActionRepository_Create_Call) RunAndReturn(run func(*models.CorporateAction) error) *CorporateActionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *CorporateActionRepository) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CorporateActionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type CorporateActionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id string
func (_e *CorporateActionRepository_Expecter) Delete(id interface{}) *CorporateActionRepository_Delete_Call {
	return &CorporateActionRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *CorporateActionRepository_Delete_Call) Run(run func(id string)) *CorporateActionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *CorporateActionRepository_Delete_Call) Return(_a0 error) *CorporateActionRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CorporateActionRepository_Delete_Call) RunAndReturn(run func(string) error) *CorporateActionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: id
func (_m *CorporateActionRepository) FindByID(id string) (*models.CorporateAction, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.CorporateAction
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.CorporateAction, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *models.CorporateAction); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CorporateAction)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CorporateActionRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type CorporateActionRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id string
func (_e *CorporateActionRepository_Expecter) FindByID(id interface{}) *CorporateActionRepository_FindByID_Call {
	return &CorporateActionRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *CorporateActionRepository_FindByID_Call) Run(run func(id string)) *CorporateActionRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *CorporateActionRepository_FindByID_Call) Return(_a0 *models.CorporateAction, _a1 error) *CorporateActionRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CorporateActionRepository_FindByID_Call) RunAndReturn(run func(string) (*models.CorporateAction, error)) *CorporateActionRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySymbol provides a mock function with given fields: symbol
func (_m *CorporateActionRepository) FindBySymbol(symbol string) ([]*models.CorporateAction, error) {
	ret := _m.Called(symbol)

	if len(ret) == 0 {
		panic("no return value specified for FindBySymbol")
	}

	var r0 []*models.CorporateAction
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*models.CorporateAction, error)); ok {
		return rf(symbol)
	}
	if rf, ok := ret.Get(0).(func(string) []*models.CorporateAction); ok {
		r0 = rf(symbol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.CorporateAction)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(symbol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CorporateActionRepository_FindBySymbol_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySymbol'
type CorporateActionRepository_FindBySymbol_Call struct {
	*mock.Call
}

// FindBySymbol is a helper method to define mock.On call
//   - symbol string
func (_e *CorporateActionRepository_Expecter) FindBySymbol(symbol interface{}) *CorporateActionRepository_FindBySymbol_Call {
	return &CorporateActionRepository_FindBySymbol_Call{Call: _e.mock.On("FindBySymbol", symbol)}
}

func (_c *CorporateActionRepository_FindBySymbol_Call) Run(run func(symbol string)) *CorporateActionRepository_FindBySymbol_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *CorporateActionRepository_FindBySymbol_Call) Return(_a0 []*models.CorporateAction, _a1 error) *CorporateActionRepository_FindBySymbol_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CorporateActionRepository_FindBySymbol_Call) RunAndReturn(run func(string) ([]*models.CorporateAction, error)) *CorporateActionRepository_FindBySymbol_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySymbolAndDateRange provides a mock function with given fields: symbol, startDate, endDate
func (_m *CorporateActionRepository) FindBySymbolAndDateRange(symbol string, startDate time.Time, endDate time.Time) ([]*models.CorporateAction, error) {
	ret := _m.Called(symbol, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for FindBySymbolAndDateRange")
	}

	var r0 []*models.CorporateAction
	var r1 error
	if rf, ok := ret.Get(0).(func(string, time.Time, time.Time) ([]*models.CorporateAction, error)); ok {
		return rf(symbol, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(string, time.Time, time.Time) []*models.CorporateAction); ok {
		r0 = rf(symbol, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.CorporateAction)
		}
	}

	if rf, ok := ret.Get(1).(func(string, time.Time, time.Time) error); ok {
		r1 = rf(symbol, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CorporateActionRepository_FindBySymbolAndDateRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySymbolAndDateRange'
type CorporateActionRepository_FindBySymbolAndDateRange_Call struct {
	*mock.Call
}

// FindBySymbolAndDateRange is a helper method to define mock.On call
//   - symbol string
//   - startDate time.Time
//   - endDate time.Time
func (_e *CorporateActionRepository_Expecter) FindBySymbolAndDateRange(symbol interface{}, startDate interface{}, endDate interface{}) *CorporateActionRepository_FindBySymbolAndDateRange_Call {
	return &CorporateActionRepository_FindBySymbolAndDateRange_Call{Call: _e.mock.On("FindBySymbolAndDateRange", symbol, startDate, endDate)}
}

func (_c *CorporateActionRepository_FindBySymbolAndDateRange_Call) Run(run func(symbol string, startDate time.Time, endDate time.Time)) *CorporateActionRepository_FindBySymbolAndDateRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(time.Time), args[2].(time.Time))
	})
	return _c
}

func (_c *CorporateActionRepository_FindBySymbolAndDateRange_Call) Return(_a0 []*models.CorporateAction, _a1 error) *CorporateActionRepository_FindBySymbolAndDateRange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CorporateActionRepository_FindBySymbolAndDateRange_Call) RunAndReturn(run func(string, time.Time, time.Time) ([]*models.CorporateAction, error)) *CorporateActionRepository_FindBySymbolAndDateRange_Call {
	_c.Call.Return(run)
	return _c
}

// FindUnapplied provides a mock function with no fields
func (_m *CorporateActionRepository) FindUnapplied() ([]*models.CorporateAction, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindUnapplied")
	}

	var r0 []*models.CorporateAction
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*models.CorporateAction, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*models.CorporateAction); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.CorporateAction)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CorporateActionRepository_FindUnapplied_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUnapplied'
type CorporateActionRepository_FindUnapplied_Call struct {
	*mock.Call
}

// FindUnapplied is a helper method to define mock.On call
func (_e *CorporateActionRepository_Expecter) FindUnapplied() *CorporateActionRepository_FindUnapplied_Call {
	return &CorporateActionRepository_FindUnapplied_Call{Call: _e.mock.On("FindUnapplied")}
}

func (_c *CorporateActionRepository_FindUnapplied_Call) Run(run func()) *CorporateActionRepository_FindUnapplied_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CorporateActionRepository_FindUnapplied_Call) Return(_a0 []*models.CorporateAction, _a1 error) *CorporateActionRepository_FindUnapplied_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CorporateActionRepository_FindUnapplied_Call) RunAndReturn(run func() ([]*models.CorporateAction, error)) *CorporateActionRepository_FindUnapplied_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: action
func (_m *CorporateActionRepository) Update(action *models.CorporateAction) error {
	ret := _m.Called(action)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.CorporateAction) error); ok {
		r0 = rf(action)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CorporateActionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CorporateActionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - action *models.CorporateAction
func (_e *CorporateActionRepository_Expecter) Update(action interface{}) *CorporateActionRepository_Update_Call {
	return &CorporateActionRepository_Update_Call{Call: _e.mock.On("Update", action)}
}

func (_c *CorporateActionRepository_Update_Call) Run(run func(action *models.CorporateAction)) *CorporateActionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.CorporateAction))
	})
	return _c
}

func (_c *CorporateActionRepository_Update_Call) Return(_a0 error) *CorporateActionRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CorporateActionRepository_Update_Call) RunAndReturn(run func(*models.CorporateAction) error) *CorporateActionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewCorporateActionRepository creates a new instance of CorporateActionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCorporateActionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CorporateActionRepository {
	mock := &CorporateActionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
