// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "github.com/lenon/portfolios/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// HoldingRepository is an autogenerated mock type for the HoldingRepository type
type HoldingRepository struct {
	mock.Mock
}

type HoldingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *HoldingRepository) EXPECT() *HoldingRepository_Expecter {
	return &HoldingRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: holding
func (_m *HoldingRepository) Create(holding *models.Holding) error {
	ret := _m.Called(holding)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Holding) error); ok {
		r0 = rf(holding)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HoldingRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type HoldingRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - holding *models.Holding
func (_e *HoldingRepository_Expecter) Create(holding interface{}) *HoldingRepository_Create_Call {
	return &HoldingRepository_Create_Call{Call: _e.mock.On("Create", holding)}
}

func (_c *HoldingRepository_Create_Call) Run(run func(holding *models.Holding)) *HoldingRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Holding))
	})
	return _c
}

func (_c *HoldingRepository_Create_Call) Return(_a0 error) *HoldingRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HoldingRepository_Create_Call) RunAndReturn(run func(*models.Holding) error) *HoldingRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *HoldingRepository) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HoldingRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type HoldingRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id string
func (_e *HoldingRepository_Expecter) Delete(id interface{}) *HoldingRepository_Delete_Call {
	return &HoldingRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *HoldingRepository_Delete_Call) Run(run func(id string)) *HoldingRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *HoldingRepository_Delete_Call) Return(_a0 error) *HoldingRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HoldingRepository_Delete_Call) RunAndReturn(run func(string) error) *HoldingRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByPortfolioIDAndSymbol provides a mock function with given fields: portfolioID, symbol
func (_m *HoldingRepository) DeleteByPortfolioIDAndSymbol(portfolioID string, symbol string) error {
	ret := _m.Called(portfolioID, symbol)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByPortfolioIDAndSymbol")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(portfolioID, symbol)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HoldingRepository_DeleteByPortfolioIDAndSymbol_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByPortfolioIDAndSymbol'
type HoldingRepository_DeleteByPortfolioIDAndSymbol_Call struct {
	*mock.Call
}

// DeleteByPortfolioIDAndSymbol is a helper method to define mock.On call
//   - portfolioID string
//   - symbol string
func (_e *HoldingRepository_Expecter) DeleteByPortfolioIDAndSymbol(portfolioID interface{}, symbol interface{}) *HoldingRepository_DeleteByPortfolioIDAndSymbol_Call {
	return &HoldingRepository_DeleteByPortfolioIDAndSymbol_Call{Call: _e.mock.On("DeleteByPortfolioIDAndSymbol", portfolioID, symbol)}
}

func (_c *HoldingRepository_DeleteByPortfolioIDAndSymbol_Call) Run(run func(portfolioID string, symbol string)) *HoldingRepository_DeleteByPortfolioIDAndSymbol_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *HoldingRepository_DeleteByPortfolioIDAndSymbol_Call) Return(_a0 error) *HoldingRepository_DeleteByPortfolioIDAndSymbol_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HoldingRepository_DeleteByPortfolioIDAndSymbol_Call) RunAndReturn(run func(string, string) error) *HoldingRepository_DeleteByPortfolioIDAndSymbol_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: id
func (_m *HoldingRepository) FindByID(id string) (*models.Holding, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Holding
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Holding, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Holding); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Holding)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HoldingRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type HoldingRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id string
func (_e *HoldingRepository_Expecter) FindByID(id interface{}) *HoldingRepository_FindByID_Call {
	return &HoldingRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *HoldingRepository_FindByID_Call) Run(run func(id string)) *HoldingRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *HoldingRepository_FindByID_Call) Return(_a0 *models.Holding, _a1 error) *HoldingRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HoldingRepository_FindByID_Call) RunAndReturn(run func(string) (*models.Holding, error)) *HoldingRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByPortfolioID provides a mock function with given fields: portfolioID
func (_m *HoldingRepository) FindByPortfolioID(portfolioID string) ([]*models.Holding, error) {
	ret := _m.Called(portfolioID)

	if len(ret) == 0 {
		panic("no return value specified for FindByPortfolioID")
	}

	var r0 []*models.Holding
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*models.Holding, error)); ok {
		return rf(portfolioID)
	}
	if rf, ok := ret.Get(0).(func(string) []*models.Holding); ok {
		r0 = rf(portfolioID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Holding)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(portfolioID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HoldingRepository_FindByPortfolioID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByPortfolioID'
type HoldingRepository_FindByPortfolioID_Call struct {
	*mock.Call
}

// FindByPortfolioID is a helper method to define mock.On call
//   - portfolioID string
func (_e *HoldingRepository_Expecter) FindByPortfolioID(portfolioID interface{}) *HoldingRepository_FindByPortfolioID_Call {
	return &HoldingRepository_FindByPortfolioID_Call{Call: _e.mock.On("FindByPortfolioID", portfolioID)}
}

func (_c *HoldingRepository_FindByPortfolioID_Call) Run(run func(portfolioID string)) *HoldingRepository_FindByPortfolioID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *HoldingRepository_FindByPortfolioID_Call) Return(_a0 []*models.Holding, _a1 error) *HoldingRepository_FindByPortfolioID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HoldingRepository_FindByPortfolioID_Call) RunAndReturn(run func(string) ([]*models.Holding, error)) *HoldingRepository_FindByPortfolioID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByPortfolioIDAndSymbol provides a mock function with given fields: portfolioID, symbol
func (_m *HoldingRepository) FindByPortfolioIDAndSymbol(portfolioID string, symbol string) (*models.Holding, error) {
	ret := _m.Called(portfolioID, symbol)

	if len(ret) == 0 {
		panic("no return value specified for FindByPortfolioIDAndSymbol")
	}

	var r0 *models.Holding
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*models.Holding, error)); ok {
		return rf(portfolioID, symbol)
	}
	if rf, ok := ret.Get(0).(func(string, string) *models.Holding); ok {
		r0 = rf(portfolioID, symbol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Holding)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(portfolioID, symbol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HoldingRepository_FindByPortfolioIDAndSymbol_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByPortfolioIDAndSymbol'
type HoldingRepository_FindByPortfolioIDAndSymbol_Call struct {
	*mock.Call
}

// FindByPortfolioIDAndSymbol is a helper method to define mock.On call
//   - portfolioID string
//   - symbol string
func (_e *HoldingRepository_Expecter) FindByPortfolioIDAndSymbol(portfolioID interface{}, symbol interface{}) *HoldingRepository_FindByPortfolioIDAndSymbol_Call {
	return &HoldingRepository_FindByPortfolioIDAndSymbol_Call{Call: _e.mock.On("FindByPortfolioIDAndSymbol", portfolioID, symbol)}
}

func (_c *HoldingRepository_FindByPortfolioIDAndSymbol_Call) Run(run func(portfolioID string, symbol string)) *HoldingRepository_FindByPortfolioIDAndSymbol_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *HoldingRepository_FindByPortfolioIDAndSymbol_Call) Return(_a0 *models.Holding, _a1 error) *HoldingRepository_FindByPortfolioIDAndSymbol_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HoldingRepository_FindByPortfolioIDAndSymbol_Call) RunAndReturn(run func(string, string) (*models.Holding, error)) *HoldingRepository_FindByPortfolioIDAndSymbol_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySymbol provides a mock function with given fields: symbol
func (_m *HoldingRepository) FindBySymbol(symbol string) ([]*models.Holding, error) {
	ret := _m.Called(symbol)

	if len(ret) == 0 {
		panic("no return value specified for FindBySymbol")
	}

	var r0 []*models.Holding
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*models.Holding, error)); ok {
		return rf(symbol)
	}
	if rf, ok := ret.Get(0).(func(string) []*models.Holding); ok {
		r0 = rf(symbol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Holding)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(symbol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HoldingRepository_FindBySymbol_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySymbol'
type HoldingRepository_FindBySymbol_Call struct {
	*mock.Call
}

// FindBySymbol is a helper method to define mock.On call
//   - symbol string
func (_e *HoldingRepository_Expecter) FindBySymbol(symbol interface{}) *HoldingRepository_FindBySymbol_Call {
	return &HoldingRepository_FindBySymbol_Call{Call: _e.mock.On("FindBySymbol", symbol)}
}

func (_c *HoldingRepository_FindBySymbol_Call) Run(run func(symbol string)) *HoldingRepository_FindBySymbol_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *HoldingRepository_FindBySymbol_Call) Return(_a0 []*models.Holding, _a1 error) *HoldingRepository_FindBySymbol_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HoldingRepository_FindBySymbol_Call) RunAndReturn(run func(string) ([]*models.Holding, error)) *HoldingRepository_FindBySymbol_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: holding
func (_m *HoldingRepository) Update(holding *models.Holding) error {
	ret := _m.Called(holding)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Holding) error); ok {
		r0 = rf(holding)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HoldingRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type HoldingRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - holding *models.Holding
func (_e *HoldingRepository_Expecter) Update(holding interface{}) *HoldingRepository_Update_Call {
	return &HoldingRepository_Update_Call{Call: _e.mock.On("Update", holding)}
}

func (_c *HoldingRepository_Update_Call) Run(run func(holding *models.Holding)) *HoldingRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Holding))
	})
	return _c
}

func (_c *HoldingRepository_Update_Call) Return(_a0 error) *HoldingRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HoldingRepository_Update_Call) RunAndReturn(run func(*models.Holding) error) *HoldingRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: holding
func (_m *HoldingRepository) Upsert(holding *models.Holding) error {
	ret := _m.Called(holding)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Holding) error); ok {
		r0 = rf(holding)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HoldingRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type HoldingRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - holding *models.Holding
func (_e *HoldingRepository_Expecter) Upsert(holding interface{}) *HoldingRepository_Upsert_Call {
	return &HoldingRepository_Upsert_Call{Call: _e.mock.On("Upsert", holding)}
}

func (_c *HoldingRepository_Upsert_Call) Run(run func(holding *models.Holding)) *HoldingRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Holding))
	})
	return _c
}

func (_c *HoldingRepository_Upsert_Call) Return(_a0 error) *HoldingRepository_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HoldingRepository_Upsert_Call) RunAndReturn(run func(*models.Holding) error) *HoldingRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewHoldingRepository creates a new instance of HoldingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHoldingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *HoldingRepository {
	mock := &HoldingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
