// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "github.com/lenon/portfolios/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// PortfolioActionRepository is an autogenerated mock type for the PortfolioActionRepository type
type PortfolioActionRepository struct {
	mock.Mock
}

type PortfolioActionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PortfolioActionRepository) EXPECT() *PortfolioActionRepository_Expecter {
	return &PortfolioActionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: action
func (_m *PortfolioActionRepository) Create(action *models.PortfolioAction) error {
	ret := _m.Called(action)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.PortfolioAction) error); ok {
		r0 = rf(action)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PortfolioActionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type PortfolioActionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - action *models.PortfolioAction
func (_e *PortfolioActionRepository_Expecter) Create(action interface{}) *PortfolioActionRepository_Create_Call {
	return &PortfolioActionRepository_Create_Call{Call: _e.mock.On("Create", action)}
}

func (_c *PortfolioActionRepository_Create_Call) Run(run func(action *models.PortfolioAction)) *PortfolioActionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.PortfolioAction))
	})
	return _c
}

func (_c *PortfolioActionRepository_Create_Call) Return(_a0 error) *PortfolioActionRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PortfolioActionRepository_Create_Call) RunAndReturn(run func(*models.PortfolioAction) error) *PortfolioActionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *PortfolioActionRepository) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PortfolioActionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type PortfolioActionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id string
func (_e *PortfolioActionRepository_Expecter) Delete(id interface{}) *PortfolioActionRepository_Delete_Call {
	return &PortfolioActionRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *PortfolioActionRepository_Delete_Call) Run(run func(id string)) *PortfolioActionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *PortfolioActionRepository_Delete_Call) Return(_a0 error) *PortfolioActionRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PortfolioActionRepository_Delete_Call) RunAndReturn(run func(string) error) *PortfolioActionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsPendingForPortfolioAndAction provides a mock function with given fields: portfolioID, corporateActionID
func (_m *PortfolioActionRepository) ExistsPendingForPortfolioAndAction(portfolioID string, corporateActionID string) (bool, error) {
	ret := _m.Called(portfolioID, corporateActionID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsPendingForPortfolioAndAction")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return rf(portfolioID, corporateActionID)
	}
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(portfolioID, corporateActionID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(portfolioID, corporateActionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PortfolioActionRepository_ExistsPendingForPortfolioAndAction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsPendingForPortfolioAndAction'
type PortfolioActionRepository_ExistsPendingForPortfolioAndAction_Call struct {
	*mock.Call
}

// ExistsPendingForPortfolioAndAction is a helper method to define mock.On call
//   - portfolioID string
//   - corporateActionID string
func (_e *PortfolioActionRepository_Expecter) ExistsPendingForPortfolioAndAction(portfolioID interface{}, corporateActionID interface{}) *PortfolioActionRepository_ExistsPendingForPortfolioAndAction_Call {
	return &PortfolioActionRepository_ExistsPendingForPortfolioAndAction_Call{Call: _e.mock.On("ExistsPendingForPortfolioAndAction", portfolioID, corporateActionID)}
}

func (_c *PortfolioActionRepository_ExistsPendingForPortfolioAndAction_Call) Run(run func(portfolioID string, corporateActionID string)) *PortfolioActionRepository_ExistsPendingForPortfolioAndAction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *PortfolioActionRepository_ExistsPendingForPortfolioAndAction_Call) Return(_a0 bool, _a1 error) *PortfolioActionRepository_ExistsPendingForPortfolioAndAction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PortfolioActionRepository_ExistsPendingForPortfolioAndAction_Call) RunAndReturn(run func(string, string) (bool, error)) *PortfolioActionRepository_ExistsPendingForPortfolioAndAction_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: id
func (_m *PortfolioActionRepository) FindByID(id string) (*models.PortfolioAction, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.PortfolioAction
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.PortfolioAction, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *models.PortfolioAction); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PortfolioAction)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PortfolioActionRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type PortfolioActionRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id string
func (_e *PortfolioActionRepository_Expecter) FindByID(id interface{}) *PortfolioActionRepository_FindByID_Call {
	return &PortfolioActionRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *PortfolioActionRepository_FindByID_Call) Run(run func(id string)) *PortfolioActionRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *PortfolioActionRepository_FindByID_Call) Return(_a0 *models.PortfolioAction, _a1 error) *PortfolioActionRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PortfolioActionRepository_FindByID_Call) RunAndReturn(run func(string) (*models.PortfolioAction, error)) *PortfolioActionRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByPortfolioID provides a mock function with given fields: portfolioID
func (_m *PortfolioActionRepository) FindByPortfolioID(portfolioID string) ([]*models.PortfolioAction, error) {
	ret := _m.Called(portfolioID)

	if len(ret) == 0 {
		panic("no return value specified for FindByPortfolioID")
	}

	var r0 []*models.PortfolioAction
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*models.PortfolioAction, error)); ok {
		return rf(portfolioID)
	}
	if rf, ok := ret.Get(0).(func(string) []*models.PortfolioAction); ok {
		r0 = rf(portfolioID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.PortfolioAction)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(portfolioID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PortfolioActionRepository_FindByPortfolioID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByPortfolioID'
type PortfolioActionRepository_FindByPortfolioID_Call struct {
	*mock.Call
}

// FindByPortfolioID is a helper method to define mock.On call
//   - portfolioID string
func (_e *PortfolioActionRepository_Expecter) FindByPortfolioID(portfolioID interface{}) *PortfolioActionRepository_FindByPortfolioID_Call {
	return &PortfolioActionRepository_FindByPortfolioID_Call{Call: _e.mock.On("FindByPortfolioID", portfolioID)}
}

func (_c *PortfolioActionRepository_FindByPortfolioID_Call) Run(run func(portfolioID string)) *PortfolioActionRepository_FindByPortfolioID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *PortfolioActionRepository_FindByPortfolioID_Call) Return(_a0 []*models.PortfolioAction, _a1 error) *PortfolioActionRepository_FindByPortfolioID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PortfolioActionRepository_FindByPortfolioID_Call) RunAndReturn(run func(string) ([]*models.PortfolioAction, error)) *PortfolioActionRepository_FindByPortfolioID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByPortfolioIDAndStatus provides a mock function with given fields: portfolioID, status
func (_m *PortfolioActionRepository) FindByPortfolioIDAndStatus(portfolioID string, status models.PortfolioActionStatus) ([]*models.PortfolioAction, error) {
	ret := _m.Called(portfolioID, status)

	if len(ret) == 0 {
		panic("no return value specified for FindByPortfolioIDAndStatus")
	}

	var r0 []*models.PortfolioAction
	var r1 error
	if rf, ok := ret.Get(0).(func(string, models.PortfolioActionStatus) ([]*models.PortfolioAction, error)); ok {
		return rf(portfolioID, status)
	}
	if rf, ok := ret.Get(0).(func(string, models.PortfolioActionStatus) []*models.PortfolioAction); ok {
		r0 = rf(portfolioID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.PortfolioAction)
		}
	}

	if rf, ok := ret.Get(1).(func(string, models.PortfolioActionStatus) error); ok {
		r1 = rf(portfolioID, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PortfolioActionRepository_FindByPortfolioIDAndStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByPortfolioIDAndStatus'
type PortfolioActionRepository_FindByPortfolioIDAndStatus_Call struct {
	*mock.Call
}

// FindByPortfolioIDAndStatus is a helper method to define mock.On call
//   - portfolioID string
//   - status models.PortfolioActionStatus
func (_e *PortfolioActionRepository_Expecter) FindByPortfolioIDAndStatus(portfolioID interface{}, status interface{}) *PortfolioActionRepository_FindByPortfolioIDAndStatus_Call {
	return &PortfolioActionRepository_FindByPortfolioIDAndStatus_Call{Call: _e.mock.On("FindByPortfolioIDAndStatus", portfolioID, status)}
}

func (_c *PortfolioActionRepository_FindByPortfolioIDAndStatus_Call) Run(run func(portfolioID string, status models.PortfolioActionStatus)) *PortfolioActionRepository_FindByPortfolioIDAndStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(models.PortfolioActionStatus))
	})
	return _c
}

func (_c *PortfolioActionRepository_FindByPortfolioIDAndStatus_Call) Return(_a0 []*models.PortfolioAction, _a1 error) *PortfolioActionRepository_FindByPortfolioIDAndStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PortfolioActionRepository_FindByPortfolioIDAndStatus_Call) RunAndReturn(run func(string, models.PortfolioActionStatus) ([]*models.PortfolioAction, error)) *PortfolioActionRepository_FindByPortfolioIDAndStatus_Call {
	_c.Call.Return(run)
	return _c
}

// FindPendingByCorporateActionID provides a mock function with given fields: corporateActionID
func (_m *PortfolioActionRepository) FindPendingByCorporateActionID(corporateActionID string) ([]*models.PortfolioAction, error) {
	ret := _m.Called(corporateActionID)

	if len(ret) == 0 {
		panic("no return value specified for FindPendingByCorporateActionID")
	}

	var r0 []*models.PortfolioAction
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*models.PortfolioAction, error)); ok {
		return rf(corporateActionID)
	}
	if rf, ok := ret.Get(0).(func(string) []*models.PortfolioAction); ok {
		r0 = rf(corporateActionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.PortfolioAction)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(corporateActionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PortfolioActionRepository_FindPendingByCorporateActionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPendingByCorporateActionID'
type PortfolioActionRepository_FindPendingByCorporateActionID_Call struct {
	*mock.Call
}

// FindPendingByCorporateActionID is a helper method to define mock.On call
//   - corporateActionID string
func (_e *PortfolioActionRepository_Expecter) FindPendingByCorporateActionID(corporateActionID interface{}) *PortfolioActionRepository_FindPendingByCorporateActionID_Call {
	return &PortfolioActionRepository_FindPendingByCorporateActionID_Call{Call: _e.mock.On("FindPendingByCorporateActionID", corporateActionID)}
}

func (_c *PortfolioActionRepository_FindPendingByCorporateActionID_Call) Run(run func(corporateActionID string)) *PortfolioActionRepository_FindPendingByCorporateActionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *PortfolioActionRepository_FindPendingByCorporateActionID_Call) Return(_a0 []*models.PortfolioAction, _a1 error) *PortfolioActionRepository_FindPendingByCorporateActionID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PortfolioActionRepository_FindPendingByCorporateActionID_Call) RunAndReturn(run func(string) ([]*models.PortfolioAction, error)) *PortfolioActionRepository_FindPendingByCorporateActionID_Call {
	_c.Call.Return(run)
	return _c
}

// FindPendingByPortfolioID provides a mock function with given fields: portfolioID
func (_m *PortfolioActionRepository) FindPendingByPortfolioID(portfolioID string) ([]*models.PortfolioAction, error) {
	ret := _m.Called(portfolioID)

	if len(ret) == 0 {
		panic("no return value specified for FindPendingByPortfolioID")
	}

	var r0 []*models.PortfolioAction
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*models.PortfolioAction, error)); ok {
		return rf(portfolioID)
	}
	if rf, ok := ret.Get(0).(func(string) []*models.PortfolioAction); ok {
		r0 = rf(portfolioID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.PortfolioAction)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(portfolioID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PortfolioActionRepository_FindPendingByPortfolioID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPendingByPortfolioID'
type PortfolioActionRepository_FindPendingByPortfolioID_Call struct {
	*mock.Call
}

// FindPendingByPortfolioID is a helper method to define mock.On call
//   - portfolioID string
func (_e *PortfolioActionRepository_Expecter) FindPendingByPortfolioID(portfolioID interface{}) *PortfolioActionRepository_FindPendingByPortfolioID_Call {
	return &PortfolioActionRepository_FindPendingByPortfolioID_Call{Call: _e.mock.On("FindPendingByPortfolioID", portfolioID)}
}

func (_c *PortfolioActionRepository_FindPendingByPortfolioID_Call) Run(run func(portfolioID string)) *PortfolioActionRepository_FindPendingByPortfolioID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *PortfolioActionRepository_FindPendingByPortfolioID_Call) Return(_a0 []*models.PortfolioAction, _a1 error) *PortfolioActionRepository_FindPendingByPortfolioID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PortfolioActionRepository_FindPendingByPortfolioID_Call) RunAndReturn(run func(string) ([]*models.PortfolioAction, error)) *PortfolioActionRepository_FindPendingByPortfolioID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: action
func (_m *PortfolioActionRepository) Update(action *models.PortfolioAction) error {
	ret := _m.Called(action)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.PortfolioAction) error); ok {
		r0 = rf(action)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PortfolioActionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type PortfolioActionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - action *models.PortfolioAction
func (_e *PortfolioActionRepository_Expecter) Update(action interface{}) *PortfolioActionRepository_Update_Call {
	return &PortfolioActionRepository_Update_Call{Call: _e.mock.On("Update", action)}
}

func (_c *PortfolioActionRepository_Update_Call) Run(run func(action *models.PortfolioAction)) *PortfolioActionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.PortfolioAction))
	})
	return _c
}

func (_c *PortfolioActionRepository_Update_Call) Return(_a0 error) *PortfolioActionRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PortfolioActionRepository_Update_Call) RunAndReturn(run func(*models.PortfolioAction) error) *PortfolioActionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewPortfolioActionRepository creates a new instance of PortfolioActionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPortfolioActionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PortfolioActionRepository {
	mock := &PortfolioActionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
