// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "github.com/lenon/portfolios/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// PortfolioRepository is an autogenerated mock type for the PortfolioRepository type
type PortfolioRepository struct {
	mock.Mock
}

type PortfolioRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PortfolioRepository) EXPECT() *PortfolioRepository_Expecter {
	return &PortfolioRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: portfolio
func (_m *PortfolioRepository) Create(portfolio *models.Portfolio) error {
	ret := _m.Called(portfolio)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Portfolio) error); ok {
		r0 = rf(portfolio)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PortfolioRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type PortfolioRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - portfolio *models.Portfolio
func (_e *PortfolioRepository_Expecter) Create(portfolio interface{}) *PortfolioRepository_Create_Call {
	return &PortfolioRepository_Create_Call{Call: _e.mock.On("Create", portfolio)}
}

func (_c *PortfolioRepository_Create_Call) Run(run func(portfolio *models.Portfolio)) *PortfolioRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Portfolio))
	})
	return _c
}

func (_c *PortfolioRepository_Create_Call) Return(_a0 error) *PortfolioRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PortfolioRepository_Create_Call) RunAndReturn(run func(*models.Portfolio) error) *PortfolioRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *PortfolioRepository) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PortfolioRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type PortfolioRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id string
func (_e *PortfolioRepository_Expecter) Delete(id interface{}) *PortfolioRepository_Delete_Call {
	return &PortfolioRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *PortfolioRepository_Delete_Call) Run(run func(id string)) *PortfolioRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *PortfolioRepository_Delete_Call) Return(_a0 error) *PortfolioRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PortfolioRepository_Delete_Call) RunAndReturn(run func(string) error) *PortfolioRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByUserIDAndName provides a mock function with given fields: userID, name
func (_m *PortfolioRepository) ExistsByUserIDAndName(userID string, name string) (bool, error) {
	ret := _m.Called(userID, name)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByUserIDAndName")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return rf(userID, name)
	}
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(userID, name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(userID, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PortfolioRepository_ExistsByUserIDAndName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByUserIDAndName'
type PortfolioRepository_ExistsByUserIDAndName_Call struct {
	*mock.Call
}

// ExistsByUserIDAndName is a helper method to define mock.On call
//   - userID string
//   - name string
func (_e *PortfolioRepository_Expecter) ExistsByUserIDAndName(userID interface{}, name interface{}) *PortfolioRepository_ExistsByUserIDAndName_Call {
	return &PortfolioRepository_ExistsByUserIDAndName_Call{Call: _e.mock.On("ExistsByUserIDAndName", userID, name)}
}

func (_c *PortfolioRepository_ExistsByUserIDAndName_Call) Run(run func(userID string, name string)) *PortfolioRepository_ExistsByUserIDAndName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *PortfolioRepository_ExistsByUserIDAndName_Call) Return(_a0 bool, _a1 error) *PortfolioRepository_ExistsByUserIDAndName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PortfolioRepository_ExistsByUserIDAndName_Call) RunAndReturn(run func(string, string) (bool, error)) *PortfolioRepository_ExistsByUserIDAndName_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: id
func (_m *PortfolioRepository) FindByID(id string) (*models.Portfolio, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Portfolio
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Portfolio, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Portfolio); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Portfolio)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PortfolioRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type PortfolioRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id string
func (_e *PortfolioRepository_Expecter) FindByID(id interface{}) *PortfolioRepository_FindByID_Call {
	return &PortfolioRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *PortfolioRepository_FindByID_Call) Run(run func(id string)) *PortfolioRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *PortfolioRepository_FindByID_Call) Return(_a0 *models.Portfolio, _a1 error) *PortfolioRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PortfolioRepository_FindByID_Call) RunAndReturn(run func(string) (*models.Portfolio, error)) *PortfolioRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function with given fields: userID
func (_m *PortfolioRepository) FindByUserID(userID string) ([]*models.Portfolio, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []*models.Portfolio
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*models.Portfolio, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) []*models.Portfolio); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Portfolio)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PortfolioRepository_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type PortfolioRepository_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - userID string
func (_e *PortfolioRepository_Expecter) FindByUserID(userID interface{}) *PortfolioRepository_FindByUserID_Call {
	return &PortfolioRepository_FindByUserID_Call{Call: _e.mock.On("FindByUserID", userID)}
}

func (_c *PortfolioRepository_FindByUserID_Call) Run(run func(userID string)) *PortfolioRepository_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *PortfolioRepository_FindByUserID_Call) Return(_a0 []*models.Portfolio, _a1 error) *PortfolioRepository_FindByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PortfolioRepository_FindByUserID_Call) RunAndReturn(run func(string) ([]*models.Portfolio, error)) *PortfolioRepository_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserIDAndName provides a mock function with given fields: userID, name
func (_m *PortfolioRepository) FindByUserIDAndName(userID string, name string) (*models.Portfolio, error) {
	ret := _m.Called(userID, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserIDAndName")
	}

	var r0 *models.Portfolio
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*models.Portfolio, error)); ok {
		return rf(userID, name)
	}
	if rf, ok := ret.Get(0).(func(string, string) *models.Portfolio); ok {
		r0 = rf(userID, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Portfolio)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(userID, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PortfolioRepository_FindByUserIDAndName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserIDAndName'
type PortfolioRepository_FindByUserIDAndName_Call struct {
	*mock.Call
}

// FindByUserIDAndName is a helper method to define mock.On call
//   - userID string
//   - name string
func (_e *PortfolioRepository_Expecter) FindByUserIDAndName(userID interface{}, name interface{}) *PortfolioRepository_FindByUserIDAndName_Call {
	return &PortfolioRepository_FindByUserIDAndName_Call{Call: _e.mock.On("FindByUserIDAndName", userID, name)}
}

func (_c *PortfolioRepository_FindByUserIDAndName_Call) Run(run func(userID string, name string)) *PortfolioRepository_FindByUserIDAndName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *PortfolioRepository_FindByUserIDAndName_Call) Return(_a0 *models.Portfolio, _a1 error) *PortfolioRepository_FindByUserIDAndName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PortfolioRepository_FindByUserIDAndName_Call) RunAndReturn(run func(string, string) (*models.Portfolio, error)) *PortfolioRepository_FindByUserIDAndName_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: portfolio
func (_m *PortfolioRepository) Update(portfolio *models.Portfolio) error {
	ret := _m.Called(portfolio)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Portfolio) error); ok {
		r0 = rf(portfolio)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PortfolioRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type PortfolioRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - portfolio *models.Portfolio
func (_e *PortfolioRepository_Expecter) Update(portfolio interface{}) *PortfolioRepository_Update_Call {
	return &PortfolioRepository_Update_Call{Call: _e.mock.On("Update", portfolio)}
}

func (_c *PortfolioRepository_Update_Call) Run(run func(portfolio *models.Portfolio)) *PortfolioRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Portfolio))
	})
	return _c
}

func (_c *PortfolioRepository_Update_Call) Return(_a0 error) *PortfolioRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PortfolioRepository_Update_Call) RunAndReturn(run func(*models.Portfolio) error) *PortfolioRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewPortfolioRepository creates a new instance of PortfolioRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPortfolioRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PortfolioRepository {
	mock := &PortfolioRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
