// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "github.com/lenon/portfolios/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// TaxLotRepository is an autogenerated mock type for the TaxLotRepository type
type TaxLotRepository struct {
	mock.Mock
}

type TaxLotRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TaxLotRepository) EXPECT() *TaxLotRepository_Expecter {
	return &TaxLotRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: taxLot
func (_m *TaxLotRepository) Create(taxLot *models.TaxLot) error {
	ret := _m.Called(taxLot)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.TaxLot) error); ok {
		r0 = rf(taxLot)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TaxLotRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TaxLotRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - taxLot *models.TaxLot
func (_e *TaxLotRepository_Expecter) Create(taxLot interface{}) *TaxLotRepository_Create_Call {
	return &TaxLotRepository_Create_Call{Call: _e.mock.On("Create", taxLot)}
}

func (_c *TaxLotRepository_Create_Call) Run(run func(taxLot *models.TaxLot)) *TaxLotRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.TaxLot))
	})
	return _c
}

func (_c *TaxLotRepository_Create_Call) Return(_a0 error) *TaxLotRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TaxLotRepository_Create_Call) RunAndReturn(run func(*models.TaxLot) error) *TaxLotRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *TaxLotRepository) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TaxLotRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type TaxLotRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id string
func (_e *TaxLotRepository_Expecter) Delete(id interface{}) *TaxLotRepository_Delete_Call {
	return &TaxLotRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *TaxLotRepository_Delete_Call) Run(run func(id string)) *TaxLotRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TaxLotRepository_Delete_Call) Return(_a0 error) *TaxLotRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TaxLotRepository_Delete_Call) RunAndReturn(run func(string) error) *TaxLotRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByPortfolioIDAndSymbol provides a mock function with given fields: portfolioID, symbol
func (_m *TaxLotRepository) DeleteByPortfolioIDAndSymbol(portfolioID string, symbol string) error {
	ret := _m.Called(portfolioID, symbol)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByPortfolioIDAndSymbol")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(portfolioID, symbol)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TaxLotRepository_DeleteByPortfolioIDAndSymbol_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByPortfolioIDAndSymbol'
type TaxLotRepository_DeleteByPortfolioIDAndSymbol_Call struct {
	*mock.Call
}

// DeleteByPortfolioIDAndSymbol is a helper method to define mock.On call
//   - portfolioID string
//   - symbol string
func (_e *TaxLotRepository_Expecter) DeleteByPortfolioIDAndSymbol(portfolioID interface{}, symbol interface{}) *TaxLotRepository_DeleteByPortfolioIDAndSymbol_Call {
	return &TaxLotRepository_DeleteByPortfolioIDAndSymbol_Call{Call: _e.mock.On("DeleteByPortfolioIDAndSymbol", portfolioID, symbol)}
}

func (_c *TaxLotRepository_DeleteByPortfolioIDAndSymbol_Call) Run(run func(portfolioID string, symbol string)) *TaxLotRepository_DeleteByPortfolioIDAndSymbol_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *TaxLotRepository_DeleteByPortfolioIDAndSymbol_Call) Return(_a0 error) *TaxLotRepository_DeleteByPortfolioIDAndSymbol_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TaxLotRepository_DeleteByPortfolioIDAndSymbol_Call) RunAndReturn(run func(string, string) error) *TaxLotRepository_DeleteByPortfolioIDAndSymbol_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: id
func (_m *TaxLotRepository) FindByID(id string) (*models.TaxLot, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.TaxLot
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.TaxLot, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *models.TaxLot); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TaxLot)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaxLotRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type TaxLotRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id string
func (_e *TaxLotRepository_Expecter) FindByID(id interface{}) *TaxLotRepository_FindByID_Call {
	return &TaxLotRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *TaxLotRepository_FindByID_Call) Run(run func(id string)) *TaxLotRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TaxLotRepository_FindByID_Call) Return(_a0 *models.TaxLot, _a1 error) *TaxLotRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaxLotRepository_FindByID_Call) RunAndReturn(run func(string) (*models.TaxLot, error)) *TaxLotRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByPortfolioID provides a mock function with given fields: portfolioID
func (_m *TaxLotRepository) FindByPortfolioID(portfolioID string) ([]*models.TaxLot, error) {
	ret := _m.Called(portfolioID)

	if len(ret) == 0 {
		panic("no return value specified for FindByPortfolioID")
	}

	var r0 []*models.TaxLot
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*models.TaxLot, error)); ok {
		return rf(portfolioID)
	}
	if rf, ok := ret.Get(0).(func(string) []*models.TaxLot); ok {
		r0 = rf(portfolioID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.TaxLot)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(portfolioID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaxLotRepository_FindByPortfolioID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByPortfolioID'
type TaxLotRepository_FindByPortfolioID_Call struct {
	*mock.Call
}

// FindByPortfolioID is a helper method to define mock.On call
//   - portfolioID string
func (_e *TaxLotRepository_Expecter) FindByPortfolioID(portfolioID interface{}) *TaxLotRepository_FindByPortfolioID_Call {
	return &TaxLotRepository_FindByPortfolioID_Call{Call: _e.mock.On("FindByPortfolioID", portfolioID)}
}

func (_c *TaxLotRepository_FindByPortfolioID_Call) Run(run func(portfolioID string)) *TaxLotRepository_FindByPortfolioID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TaxLotRepository_FindByPortfolioID_Call) Return(_a0 []*models.TaxLot, _a1 error) *TaxLotRepository_FindByPortfolioID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaxLotRepository_FindByPortfolioID_Call) RunAndReturn(run func(string) ([]*models.TaxLot, error)) *TaxLotRepository_FindByPortfolioID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByPortfolioIDAndSymbol provides a mock function with given fields: portfolioID, symbol
func (_m *TaxLotRepository) FindByPortfolioIDAndSymbol(portfolioID string, symbol string) ([]*models.TaxLot, error) {
	ret := _m.Called(portfolioID, symbol)

	if len(ret) == 0 {
		panic("no return value specified for FindByPortfolioIDAndSymbol")
	}

	var r0 []*models.TaxLot
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) ([]*models.TaxLot, error)); ok {
		return rf(portfolioID, symbol)
	}
	if rf, ok := ret.Get(0).(func(string, string) []*models.TaxLot); ok {
		r0 = rf(portfolioID, symbol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.TaxLot)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(portfolioID, symbol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaxLotRepository_FindByPortfolioIDAndSymbol_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByPortfolioIDAndSymbol'
type TaxLotRepository_FindByPortfolioIDAndSymbol_Call struct {
	*mock.Call
}

// FindByPortfolioIDAndSymbol is a helper method to define mock.On call
//   - portfolioID string
//   - symbol string
func (_e *TaxLotRepository_Expecter) FindByPortfolioIDAndSymbol(portfolioID interface{}, symbol interface{}) *TaxLotRepository_FindByPortfolioIDAndSymbol_Call {
	return &TaxLotRepository_FindByPortfolioIDAndSymbol_Call{Call: _e.mock.On("FindByPortfolioIDAndSymbol", portfolioID, symbol)}
}

func (_c *TaxLotRepository_FindByPortfolioIDAndSymbol_Call) Run(run func(portfolioID string, symbol string)) *TaxLotRepository_FindByPortfolioIDAndSymbol_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *TaxLotRepository_FindByPortfolioIDAndSymbol_Call) Return(_a0 []*models.TaxLot, _a1 error) *TaxLotRepository_FindByPortfolioIDAndSymbol_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaxLotRepository_FindByPortfolioIDAndSymbol_Call) RunAndReturn(run func(string, string) ([]*models.TaxLot, error)) *TaxLotRepository_FindByPortfolioIDAndSymbol_Call {
	_c.Call.Return(run)
	return _c
}

// FindByTransactionID provides a mock function with given fields: transactionID
func (_m *TaxLotRepository) FindByTransactionID(transactionID string) ([]*models.TaxLot, error) {
	ret := _m.Called(transactionID)

	if len(ret) == 0 {
		panic("no return value specified for FindByTransactionID")
	}

	var r0 []*models.TaxLot
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*models.TaxLot, error)); ok {
		return rf(transactionID)
	}
	if rf, ok := ret.Get(0).(func(string) []*models.TaxLot); ok {
		r0 = rf(transactionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.TaxLot)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(transactionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaxLotRepository_FindByTransactionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByTransactionID'
type TaxLotRepository_FindByTransactionID_Call struct {
	*mock.Call
}

// FindByTransactionID is a helper method to define mock.On call
//   - transactionID string
func (_e *TaxLotRepository_Expecter) FindByTransactionID(transactionID interface{}) *TaxLotRepository_FindByTransactionID_Call {
	return &TaxLotRepository_FindByTransactionID_Call{Call: _e.mock.On("FindByTransactionID", transactionID)}
}

func (_c *TaxLotRepository_FindByTransactionID_Call) Run(run func(transactionID string)) *TaxLotRepository_FindByTransactionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TaxLotRepository_FindByTransactionID_Call) Return(_a0 []*models.TaxLot, _a1 error) *TaxLotRepository_FindByTransactionID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaxLotRepository_FindByTransactionID_Call) RunAndReturn(run func(string) ([]*models.TaxLot, error)) *TaxLotRepository_FindByTransactionID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: taxLot
func (_m *TaxLotRepository) Update(taxLot *models.TaxLot) error {
	ret := _m.Called(taxLot)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.TaxLot) error); ok {
		r0 = rf(taxLot)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TaxLotRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type TaxLotRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - taxLot *models.TaxLot
func (_e *TaxLotRepository_Expecter) Update(taxLot interface{}) *TaxLotRepository_Update_Call {
	return &TaxLotRepository_Update_Call{Call: _e.mock.On("Update", taxLot)}
}

func (_c *TaxLotRepository_Update_Call) Run(run func(taxLot *models.TaxLot)) *TaxLotRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.TaxLot))
	})
	return _c
}

func (_c *TaxLotRepository_Update_Call) Return(_a0 error) *TaxLotRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TaxLotRepository_Update_Call) RunAndReturn(run func(*models.TaxLot) error) *TaxLotRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewTaxLotRepository creates a new instance of TaxLotRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaxLotRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaxLotRepository {
	mock := &TaxLotRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
