// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "github.com/lenon/portfolios/internal/models"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// TransactionRepository is an autogenerated mock type for the TransactionRepository type
type TransactionRepository struct {
	mock.Mock
}

type TransactionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TransactionRepository) EXPECT() *TransactionRepository_Expecter {
	return &TransactionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: transaction
func (_m *TransactionRepository) Create(transaction *models.Transaction) error {
	ret := _m.Called(transaction)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Transaction) error); ok {
		r0 = rf(transaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransactionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TransactionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - transaction *models.Transaction
func (_e *TransactionRepository_Expecter) Create(transaction interface{}) *TransactionRepository_Create_Call {
	return &TransactionRepository_Create_Call{Call: _e.mock.On("Create", transaction)}
}

func (_c *TransactionRepository_Create_Call) Run(run func(transaction *models.Transaction)) *TransactionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Transaction))
	})
	return _c
}

func (_c *TransactionRepository_Create_Call) Return(_a0 error) *TransactionRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransactionRepository_Create_Call) RunAndReturn(run func(*models.Transaction) error) *TransactionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *TransactionRepository) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransactionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type TransactionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id string
func (_e *TransactionRepository_Expecter) Delete(id interface{}) *TransactionRepository_Delete_Call {
	return &TransactionRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *TransactionRepository_Delete_Call) Run(run func(id string)) *TransactionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TransactionRepository_Delete_Call) Return(_a0 error) *TransactionRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransactionRepository_Delete_Call) RunAndReturn(run func(string) error) *TransactionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByImportBatchID provides a mock function with given fields: batchID
func (_m *TransactionRepository) DeleteByImportBatchID(batchID string) error {
	ret := _m.Called(batchID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByImportBatchID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(batchID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransactionRepository_DeleteByImportBatchID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByImportBatchID'
type TransactionRepository_DeleteByImportBatchID_Call struct {
	*mock.Call
}

// DeleteByImportBatchID is a helper method to define mock.On call
//   - batchID string
func (_e *TransactionRepository_Expecter) DeleteByImportBatchID(batchID interface{}) *TransactionRepository_DeleteByImportBatchID_Call {
	return &TransactionRepository_DeleteByImportBatchID_Call{Call: _e.mock.On("DeleteByImportBatchID", batchID)}
}

func (_c *TransactionRepository_DeleteByImportBatchID_Call) Run(run func(batchID string)) *TransactionRepository_DeleteByImportBatchID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TransactionRepository_DeleteByImportBatchID_Call) Return(_a0 error) *TransactionRepository_DeleteByImportBatchID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransactionRepository_DeleteByImportBatchID_Call) RunAndReturn(run func(string) error) *TransactionRepository_DeleteByImportBatchID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: id
func (_m *TransactionRepository) FindByID(id string) (*models.Transaction, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Transaction, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Transaction); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type TransactionRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id string
func (_e *TransactionRepository_Expecter) FindByID(id interface{}) *TransactionRepository_FindByID_Call {
	return &TransactionRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *TransactionRepository_FindByID_Call) Run(run func(id string)) *TransactionRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TransactionRepository_FindByID_Call) Return(_a0 *models.Transaction, _a1 error) *TransactionRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TransactionRepository_FindByID_Call) RunAndReturn(run func(string) (*models.Transaction, error)) *TransactionRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByPortfolioID provides a mock function with given fields: portfolioID
func (_m *TransactionRepository) FindByPortfolioID(portfolioID string) ([]*models.Transaction, error) {
	ret := _m.Called(portfolioID)

	if len(ret) == 0 {
		panic("no return value specified for FindByPortfolioID")
	}

	var r0 []*models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*models.Transaction, error)); ok {
		return rf(portfolioID)
	}
	if rf, ok := ret.Get(0).(func(string) []*models.Transaction); ok {
		r0 = rf(portfolioID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(portfolioID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionRepository_FindByPortfolioID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByPortfolioID'
type TransactionRepository_FindByPortfolioID_Call struct {
	*mock.Call
}

// FindByPortfolioID is a helper method to define mock.On call
//   - portfolioID string
func (_e *TransactionRepository_Expecter) FindByPortfolioID(portfolioID interface{}) *TransactionRepository_FindByPortfolioID_Call {
	return &TransactionRepository_FindByPortfolioID_Call{Call: _e.mock.On("FindByPortfolioID", portfolioID)}
}

func (_c *TransactionRepository_FindByPortfolioID_Call) Run(run func(portfolioID string)) *TransactionRepository_FindByPortfolioID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TransactionRepository_FindByPortfolioID_Call) Return(_a0 []*models.Transaction, _a1 error) *TransactionRepository_FindByPortfolioID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TransactionRepository_FindByPortfolioID_Call) RunAndReturn(run func(string) ([]*models.Transaction, error)) *TransactionRepository_FindByPortfolioID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByPortfolioIDAndSymbol provides a mock function with given fields: portfolioID, symbol
func (_m *TransactionRepository) FindByPortfolioIDAndSymbol(portfolioID string, symbol string) ([]*models.Transaction, error) {
	ret := _m.Called(portfolioID, symbol)

	if len(ret) == 0 {
		panic("no return value specified for FindByPortfolioIDAndSymbol")
	}

	var r0 []*models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) ([]*models.Transaction, error)); ok {
		return rf(portfolioID, symbol)
	}
	if rf, ok := ret.Get(0).(func(string, string) []*models.Transaction); ok {
		r0 = rf(portfolioID, symbol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(portfolioID, symbol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionRepository_FindByPortfolioIDAndSymbol_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByPortfolioIDAndSymbol'
type TransactionRepository_FindByPortfolioIDAndSymbol_Call struct {
	*mock.Call
}

// FindByPortfolioIDAndSymbol is a helper method to define mock.On call
//   - portfolioID string
//   - symbol string
func (_e *TransactionRepository_Expecter) FindByPortfolioIDAndSymbol(portfolioID interface{}, symbol interface{}) *TransactionRepository_FindByPortfolioIDAndSymbol_Call {
	return &TransactionRepository_FindByPortfolioIDAndSymbol_Call{Call: _e.mock.On("FindByPortfolioIDAndSymbol", portfolioID, symbol)}
}

func (_c *TransactionRepository_FindByPortfolioIDAndSymbol_Call) Run(run func(portfolioID string, symbol string)) *TransactionRepository_FindByPortfolioIDAndSymbol_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *TransactionRepository_FindByPortfolioIDAndSymbol_Call) Return(_a0 []*models.Transaction, _a1 error) *TransactionRepository_FindByPortfolioIDAndSymbol_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TransactionRepository_FindByPortfolioIDAndSymbol_Call) RunAndReturn(run func(string, string) ([]*models.Transaction, error)) *TransactionRepository_FindByPortfolioIDAndSymbol_Call {
	_c.Call.Return(run)
	return _c
}

// FindByPortfolioIDWithFilters provides a mock function with given fields: portfolioID, symbol, startDate, endDate
func (_m *TransactionRepository) FindByPortfolioIDWithFilters(portfolioID string, symbol *string, startDate *time.Time, endDate *time.Time) ([]*models.Transaction, error) {
	ret := _m.Called(portfolioID, symbol, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for FindByPortfolioIDWithFilters")
	}

	var r0 []*models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *string, *time.Time, *time.Time) ([]*models.Transaction, error)); ok {
		return rf(portfolioID, symbol, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(string, *string, *time.Time, *time.Time) []*models.Transaction); ok {
		r0 = rf(portfolioID, symbol, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *string, *time.Time, *time.Time) error); ok {
		r1 = rf(portfolioID, symbol, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionRepository_FindByPortfolioIDWithFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByPortfolioIDWithFilters'
type TransactionRepository_FindByPortfolioIDWithFilters_Call struct {
	*mock.Call
}

// FindByPortfolioIDWithFilters is a helper method to define mock.On call
//   - portfolioID string
//   - symbol *string
//   - startDate *time.Time
//   - endDate *time.Time
func (_e *TransactionRepository_Expecter) FindByPortfolioIDWithFilters(portfolioID interface{}, symbol interface{}, startDate interface{}, endDate interface{}) *TransactionRepository_FindByPortfolioIDWithFilters_Call {
	return &TransactionRepository_FindByPortfolioIDWithFilters_Call{Call: _e.mock.On("FindByPortfolioIDWithFilters", portfolioID, symbol, startDate, endDate)}
}

func (_c *TransactionRepository_FindByPortfolioIDWithFilters_Call) Run(run func(portfolioID string, symbol *string, startDate *time.Time, endDate *time.Time)) *TransactionRepository_FindByPortfolioIDWithFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*string), args[2].(*time.Time), args[3].(*time.Time))
	})
	return _c
}

func (_c *TransactionRepository_FindByPortfolioIDWithFilters_Call) Return(_a0 []*models.Transaction, _a1 error) *TransactionRepository_FindByPortfolioIDWithFilters_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TransactionRepository_FindByPortfolioIDWithFilters_Call) RunAndReturn(run func(string, *string, *time.Time, *time.Time) ([]*models.Transaction, error)) *TransactionRepository_FindByPortfolioIDWithFilters_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: transaction
func (_m *TransactionRepository) Update(transaction *models.Transaction) error {
	ret := _m.Called(transaction)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Transaction) error); ok {
		r0 = rf(transaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransactionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type TransactionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - transaction *models.Transaction
func (_e *TransactionRepository_Expecter) Update(transaction interface{}) *TransactionRepository_Update_Call {
	return &TransactionRepository_Update_Call{Call: _e.mock.On("Update", transaction)}
}

func (_c *TransactionRepository_Update_Call) Run(run func(transaction *models.Transaction)) *TransactionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Transaction))
	})
	return _c
}

func (_c *TransactionRepository_Update_Call) Return(_a0 error) *TransactionRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransactionRepository_Update_Call) RunAndReturn(run func(*models.Transaction) error) *TransactionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewTransactionRepository creates a new instance of TransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionRepository {
	mock := &TransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
