with-expecter: true
dir: "internal/mocks"
outpkg: mocks
filename: "{{.InterfaceName}}.go"
mockname: "{{.InterfaceName}}"
packages:
  github.com/lenon/portfolios/internal/repository:
    interfaces:
      UserRepository:
      PortfolioRepository:
      TransactionRepository:
      HoldingRepository:
      TaxLotRepository:
      CorporateActionRepository:
      PortfolioActionRepository:
